# Workflow for live database platform tests.
name: Database platform tests

on:
  pull_request:
    paths:
      - 'R/**'
      - 'tests/**'
      - 'inst/test-config/hades-database-platforms.yml'
      - '.github/workflows/database-platform-tests.yml'
  push:
    paths:
      - 'R/**'
      - 'tests/**'
      - 'inst/test-config/hades-database-platforms.yml'
      - '.github/workflows/database-platform-tests.yml'
  workflow_dispatch:

jobs:
  database-test:
    name: Database test (${{ matrix.dbms }})
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        include:
          - dbms: postgresql
            environment: test-postgresql

    environment: ${{ matrix.environment }}

    env:
      GITHUB_PAT: ${{ secrets.GH_TOKEN }}
      HADES_DATABASE_TEST: 'true'
      HADES_TEST_DBMS: ${{ matrix.dbms }}

      CDM5_POSTGRESQL_CDM_SCHEMA: ${{ secrets.CDM5_POSTGRESQL_CDM54_SCHEMA }}
      CDM5_POSTGRESQL_OHDSI_SCHEMA: ${{ secrets.CDM5_POSTGRESQL_OHDSI_SCHEMA }}
      CDM5_POSTGRESQL_PASSWORD: ${{ secrets.CDM5_POSTGRESQL_PASSWORD }}
      CDM5_POSTGRESQL_SERVER: ${{ secrets.CDM5_POSTGRESQL_SERVER }}
      CDM5_POSTGRESQL_USER: ${{ secrets.CDM5_POSTGRESQL_USER }}

    steps:
      - uses: actions/checkout@v4

      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: release

      - name: Query dependencies
        run: |
          install.packages('remotes')
          saveRDS(remotes::dev_package_deps(dependencies = TRUE), ".github/depends.Rds", version = 2)
          writeLines(sprintf("R-%i.%i", getRversion()$major, getRversion()$minor), ".github/R-version")
        shell: Rscript {0}

      - name: Cache R packages
        uses: actions/cache@v4
        with:
          path: ${{ env.R_LIBS_USER }}
          key: ${{ runner.os }}-${{ hashFiles('.github/R-version') }}-1-${{ hashFiles('.github/depends.Rds') }}
          restore-keys: ${{ runner.os }}-${{ hashFiles('.github/R-version') }}-1-

      - name: Install system dependencies
        if: runner.os == 'Linux'
        run: |
          sudo apt-get install -y make
          sudo apt-get install -y default-jdk
          sudo apt-get install -y libcurl4-openssl-dev
          sudo apt-get install -y libssl-dev
          sudo apt-get install -y libglpk-dev
          while read -r cmd
          do
            eval sudo $cmd
          done < <(Rscript -e 'writeLines(remotes::system_requirements("ubuntu", "22.04"))')          

      - uses: actions/setup-java@v4
        with:
          distribution: corretto
          java-version: '8'

      - name: Install libssh
        if: runner.os == 'Linux'
        run: |    
          sudo apt-get install libssh-dev

      - name: Install dependencies
        run: |
          install.packages("cachem")
          remotes::install_deps(dependencies = TRUE, INSTALL_opts=c("--no-multiarch"))
          remotes::install_cran("rcmdcheck")
        shell: Rscript {0}

      - name: Check
        env:
          _R_CHECK_CRAN_INCOMING_REMOTE_: false
        run: rcmdcheck::rcmdcheck(args = c("--no-manual", "--no-build-vignettes", "--ignore-vignettes", "--no-examples"), error_on = "warning", check_dir = "check")
        shell: Rscript {0}
